[".local/share/nvim/site/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"
[".vim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"
[".local/share/enhancd"]
    type = "archive"
    url = "https://github.com/b4b4r07/enhancd/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".local/share/forgit.zsh"]
    type = "file"
    url = "https://raw.githubusercontent.com/wfxr/forgit/master/forgit.plugin.zsh"
    refreshPeriod = "168h"
[".local/share/zsh-autoswitch-virtualenv.zsh"]
    type = "file"
    url = "https://raw.githubusercontent.com/MichaelAquilina/zsh-autoswitch-virtualenv/master/autoswitch_virtualenv.plugin.zsh"
    refreshPeriod = "168h"
[".local/share/zsh-termsupport.zsh"]
    type = "file"
    url = "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/lib/termsupport.zsh"
    refreshPeriod = "168h"
[".local/share/nord_dir_colors"]
    type = "file"
    url = "https://raw.githubusercontent.com/arcticicestudio/nord-dircolors/develop/src/dir_colors"
    refreshPeriod = "168h"
