[".local/share/nvim/site/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"
[".vim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"
[".local/share/enhancd"]
    type = "archive"
    url = "https://github.com/b4b4r07/enhancd/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".local/share/forgit.zsh"]
    type = "file"
    url = "https://raw.githubusercontent.com/wfxr/forgit/master/forgit.plugin.zsh"
    refreshPeriod = "168h"
[".local/share/zsh-autoswitch-virtualenv.zsh"]
    type = "file"
    url = "https://raw.githubusercontent.com/MichaelAquilina/zsh-autoswitch-virtualenv/master/autoswitch_virtualenv.plugin.zsh"
    refreshPeriod = "168h"
[".local/share/zsh-termsupport.zsh"]
    type = "file"
    url = "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/lib/termsupport.zsh"
    refreshPeriod = "168h"
[".local/share/zsh-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    include = ["*/*.zsh", "*/.version", "*/.revision-hash", "*/highlighters/**"]
{{ if eq .theme "nord" -}}
[".local/share/konsole/{{ .theme }}.colorscheme"]
    type = "file"
    url = "https://raw.githubusercontent.com/arcticicestudio/nord-konsole/develop/src/nord.colorscheme"
    refreshPeriod = "168h"
{{- else if eq .theme "catppuccin" }}
[".config/kitty/themes"]
    type = "archive"
    refreshPeriod = "168h"
    url = "https://github.com/catppuccin/kitty/archive/main.tar.gz"
    stripComponents = 2
    include = ["*/themes/*.conf"]
[".local/share/konsole"]
    type = "archive"
    refreshPeriod = "168h"
    url = "https://github.com/catppuccin/konsole/archive/main.tar.gz"
    stripComponents = 1
    include = ["*/*.colorscheme"]
[".config/lazygit"]
    type = "archive"
    refreshPeriod = "168h"
    url = "https://github.com/catppuccin/lazygit/archive/main.tar.gz"
    stripComponents = 2
    include = ["*/themes/*.yml"]
[".config/gitui"]
    type = "archive"
    refreshPeriod = "168h"
    url = "https://github.com/catppuccin/gitui/archive/master.tar.gz"
    stripComponents = 2
    include = ["*/theme/*.ron"]
[".local/share/catppuccin-zsh-syntax-highlighting"]
    type = "archive"
    refreshPeriod = "168h"
    url = "https://github.com/catppuccin/zsh-syntax-highlighting/archive/main.tar.gz"
    stripComponents = 2
    include = ["*/themes/*.zsh"]
    exact = true
[".config/starship/themes"]
    type = "archive"
    refreshPeriod = "168h"
    url = "https://github.com/catppuccin/starship/archive/main.tar.gz"
    stripComponents = 2
    include = ["*/palettes/*.toml"]
[".config/bat/themes"]
    type = "archive"
    refreshPeriod = "168h"
    url = "https://github.com/catppuccin/bat/archive/main.tar.gz"
    stripComponents = 1
    include = ["*/*.tmTheme"]
{{- else if eq .theme "dracula" }}
[".config/kitty/themes/{{ .theme }}.conf"]
    type = "file"
    refreshPeriod = "168h"
    url = "https://raw.githubusercontent.com/dracula/kitty/master/dracula.conf"
[".config/tig/config"]
    type = "file"
    url = "https://raw.githubusercontent.com/dracula/tig/master/config"
    refreshPeriod = "168h"
[".local/share/konsole/{{ .theme }}.colorscheme"]
    type = "file"
    url = "https://raw.githubusercontent.com/dracula/konsole/master/Dracula.colorscheme"
    refreshPeriod = "168h"
[".local/share/dracula-zsh-syntax-highlighting.zsh"]
    type = "file"
    url = "https://raw.githubusercontent.com/dracula/zsh-syntax-highlighting/master/zsh-syntax-highlighting.sh"
    refreshPeriod = "168h"
{{- end }}
